노래 상세 정보 버그 수정
woowacourse-teams/2023-diggin-room pull request #194
Opened 2023-08-08 01:18 UTC by whk06061

## 관련 이슈번호
- #189 

## 작업 사항
- 노래 상세 정보 다이얼로그가 여러 번 뜨는 버그 수정
- 노래 제목 잘리는 버그 수정 

## 기타 사항
<br/>

2023-08-08 01:57 UTC, boogi-woogi commented on android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roominfoview/DefaultShowRoomInfoListener.kt
> +            dialog?.show((context as RoomActivity).supportFragmentManager, "")
dialog에서 context를 얻어올 순 없을까요?

2023-08-08 01:58 UTC, DYGames requested changes

2023-08-08 01:58 UTC, DYGames commented on android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roominfoview/DefaultShowRoomInfoListener.kt
> +    private var dialog: TrackInfoDialog? = null
lateinit

2023-08-08 01:58 UTC, DYGames commented on android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roominfoview/DefaultShowRoomInfoListener.kt
> +        if (dialog?.isAdded == false) {
!

2023-08-08 01:58 UTC, DYGames commented on android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roominfoview/DefaultShowRoomInfoListener.kt
> +            dialog?.show((context as RoomActivity).supportFragmentManager, "")
RoomActivity와 강한 결합

2023-08-08 01:58 UTC, DYGames commented on android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roominfoview/DefaultShowRoomInfoListener.kt
> +        if (dialog == null) {
lateinit되었는지 검사

2023-08-09 02:58 UTC, DYGames approved these changes

2023-08-09 04:35 UTC, boogi-woogi approved these changes

2023-08-09 04:35 UTC, merged