feat: 댓글 기능을 구현한다.
woowacourse-teams/2023-diggin-room pull request #225
Opened 2023-08-11 13:30 UTC by Songusika

## 관련 이슈번호
- #207 

## 작업 사항
유저는 룸에 댓글을 달수 있다.
 - 이때 없는 룸이라면 예외를 반환한다.
 
유저는 룸의 모든 댓글을 볼 수 있다.
 - 이때 없는 룸이라면 예외를 반환한다.
 
유저는 자신의 댓글을 수정할 수 있다.
 - 이때 없는 룸이라면 예외를 반환한다.
 - 없는 댓글일 경우 예외를 반환한다.
 - 이때 요청한 댓글의 룸과 실제 댓글의 룸이 다르면 예외를 반환한다.
 - 자신의 댓글이 아니라면 예외를 반환한다.

유저는 자신의 댓글을 삭제할 수 있다.
 - 이때 없는 룸이라면 예외를 반환한다.
 - 없는 댓글일 경우 예외를 반환한다.
 - 이때 요청한 댓글의 룸과 실제 댓글의 룸이 다르면 예외를 반환한다.
 - 자신의 댓글이 아니라면 예외를 반환한다.

## 기타 사항
Flyway를 위한 SQL 작성 시 clob 같은 경우 MySQL에서 지원하지 않습니다.
해당 데이터타입은 `LONGTEXT` 로 작성해야합니다.
단, 하이버네이트가 생성하는 SQL 의 경우 CLOB 으로 생성하기 때문에 복사해서 사용 시 문제가 발생할 수 있습니다.
해당 문제는 H2의 모드를 MySQL 모드로 사용해도 발생합니다. (`jdbc:h2:mem:testdb;MODE=MySQL`)
따라서 로컬 환경에서도 MySQL 로 통일을 하는 방법 등 이를 해결할 수 있는 방법을 고안하여야 합니다

2023-08-11 13:35 UTC, 0chil commented
좋았어

2023-08-11 15:59 UTC, 0chil requested changes
고생 많으셨습니다~! 너무 훌륭하게 잘 구현해주신 것 같습니다.
다듬어볼 만한 부분들 커멘트 남겼습니다!

\+ 추가로 궁금한 사항
Comment는 모두 룸에 관련된 내용인것 같습니다. 룸의 하위 도메인이라고도 할 수 있겠죠.
Room 객체와 연관짓지 않고 서비스 레벨에서 구현한 이유가 있을까요?

후에 우리가 Comment와 관련된 도메인을 확장하거나 다른 부분에서 활용한다고 했을 때, 
룸 객체에서 가져오는게 아니라, DB에서 직접 뽑아오고 있으므로 확장이 어려워지는게 걱정됩니다.

DB가 아예 없다고 가정하고 댓글 기능을 구현한다고 가정해보면, 어딘가에 댓글을 따로 보관하기보다는, 룸이 List<Comment>를 가지게 만들지  않을까요?
그래서 지금 구조는 너무 DB에 종속적인 설계라고 생각이 들어요.

사용하지 않을 룸의 데이터를 가져오는 것 때문에 성능상의 이슈가 걱정되는 거라면,
추후에 [Spring Boot Cache](https://pamyferret.tistory.com/8)를 활용해보면 어떨까요?

2023-08-11 15:59 UTC, 0chil commented on backend/src/main/java/com/digginroom/digginroom/service/CommentService.java
> +        validateSameRoomAndOwner(member, roomId, comment);
`validateWriteable()` 이런 네이밍은 어떨까요?

내부에서 '룸이 같은지', '주인이 같은지' 확인했으니, 
이 행위를 '쓰기 권한이 있다' 라고 한단계 추상화해서 표현해볼 수 있을 것 같아요.

2023-08-11 15:59 UTC, 0chil commented on backend/src/main/java/com/digginroom/digginroom/service/CommentService.java
> +        validateSameRoomAndOwner(member, roomId, comment);
이 리뷰를 반영하신다면, 메서드 인자 중 어떤 인자가 가장 중요한 인자인지도 생각해볼 수 있을 것 같아요.

comment에 쓰기 권한(수정, 삭제 등)이 있는지 검사하는게 목적이므로
comment가 가장 첫번째 인자로 온다면
`validateWriteable(comment, roomId, member)` 이런 식으로 의도가 더 잘 표현되겠네요.

2023-08-11 15:59 UTC, 0chil commented on backend/src/main/java/com/digginroom/digginroom/service/CommentService.java
> +        return new CommentsResponse(comments.stream()
이미 찾은 객체들을 반환하므로
`findRoomComments()` -> `getRoomComments()`로,

복수 개의 객체들을 찾아오므로
`commentRepository.findCommentByRoomId()` 는 
`commentRepository.findCommentsByRoomId()` 로 변경하면 더 좋을 것 같아요.

2023-08-11 15:59 UTC, 0chil commented on backend/src/test/java/com/digginroom/digginroom/controller/TestFixture.java
> +//TODO: 픽스쳐 분리
이건 완료된 사항일까요?

2023-08-13 07:06 UTC, kong-hana01 reviewed
굿굿

2023-08-13 07:06 UTC, kong-hana01 commented on backend/src/main/resources/db/migration/V4__comment_added.sql
> +    member_id  bigint,
확인해보니 큰 문제는 없어보이네요!

2023-08-16 10:10 UTC, Songusika commented on backend/src/main/resources/db/migration/V4__comment_added.sql
> +    member_id  bigint,
지금 확인 해보니까 FK 제약 조건이 누락되었네요 의도한건 아니였습니다. 추가해서 반영할게요~

2023-08-16 10:24 UTC, Songusika commented on backend/src/main/java/com/digginroom/digginroom/domain/Comment.java
> +        return this;
해당 `update()` 메서드를 사용하는 서비스 계층에서 가독성이 좋게 하기 위해서 `return this;` 로 처리하였습니다.
```java
    public Comment update(...) {
        Comment comment = commentRepository.getCommentById(commentId);
        validateSameRoomAndOwner(member, roomId, comment);
        return comment.updateComment(request.comment());
    }
```

2023-08-16 10:26 UTC, Songusika commented on backend/src/main/java/com/digginroom/digginroom/repository/CommentRepository.java
> +        return findCommentById(id).orElseThrow(NotFoundException::new);
현재 저희 어플리케이션에서 다른 서비스가 다른 서비스를 참조하는 일이 많습니다.
그 이유는 중복된 예외 처리를 하지 않기 위함인데요
위와 같이 Repository 계층에서 처리하면 서비스가 다른 서비스 계층을 참조하는 것을 어느정도 방지할 수 있고,
서비스 코드 전반적으로 가독성이 더 좋아지지 않을까합니다.

2023-08-16 10:27 UTC, Songusika commented on backend/src/main/java/com/digginroom/digginroom/domain/Comment.java
> +    public Comment(final Long roomId, final String comment, final Member member) {
반영하였습니다.

2023-08-16 10:28 UTC, Songusika commented on backend/src/main/java/com/digginroom/digginroom/domain/Comment.java
> +    private Member member;
현재 댓글을 통해서 룸을 탐색할 일은 비즈니스 적으로 없고, 앞으로도 없을 거라고 판단했습니다.
단 댓글을 작성한 멤버와 같은 경우 추후 프로필 사진 등의 필요한 정보가 더 추가될 수 있을 거라고 판단하여 
`Member` 엔티티를 참조하도록 하였습니다.

2023-08-16 10:28 UTC, Songusika commented on backend/src/main/java/com/digginroom/digginroom/domain/BaseEntity.java
> +public abstract class BaseEntity {
저는 콩하나가 좋습니다.

2023-08-16 10:29 UTC, Songusika commented on backend/src/main/java/com/digginroom/digginroom/controller/CommentController.java
> +            @Auth final Long memberId,
반영했습니다.

2023-08-16 10:32 UTC, Songusika commented on backend/src/test/java/com/digginroom/digginroom/controller/TestFixture.java
> +//TODO: 픽스쳐 분리
픽스쳐 패키지 이동했습니다.

2023-08-16 10:38 UTC, Songusika commented on backend/src/main/java/com/digginroom/digginroom/service/CommentService.java
> +        return new CommentsResponse(comments.stream()
반영했습니다~

2023-08-16 10:43 UTC, Songusika commented on backend/src/main/java/com/digginroom/digginroom/domain/Comment.java
> +    private String comment;
저는 틀틀개발자였네요 🦷

2023-08-16 10:45 UTC, Songusika commented on backend/src/main/java/com/digginroom/digginroom/controller/dto/CommentResponse.java
> +
intelliJ second format 문제였네요... 🤛

2023-08-16 11:34 UTC, 0chil approved these changes

2023-08-16 11:34 UTC, kong-hana01 approved these changes

2023-08-16 11:36 UTC, merged