CommentState 관련있는 것 끼리 묶고 댓글 버그 수정
woowacourse-teams/2023-diggin-room pull request #287
Opened 2023-09-07 05:06 UTC by whk06061

## 관련 이슈번호
- #270 

## 작업 사항
<br/>

## 기타 사항
<br/>

2023-09-08 05:47 UTC, DYGames approved these changes

2023-09-08 06:12 UTC, boogi-woogi requested changes
고생하셨습니다~ 개선할 수 있는 부분들을 코멘트로 남겨두었습니다~

2023-09-08 06:12 UTC, boogi-woogi commented on android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roominfoview/comment/CommentViewModel.kt
> +    }
`showMessage()`라는 것은 `viewModel이 직접 view에 어떤 메시지를 띄운다.`라는 것처럼 느껴질 수도 있다고 생각합니다. 다른 함수 네이밍을 사용하는 것은 어떨까요?

2023-09-08 06:12 UTC, boogi-woogi commented on android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roominfoview/comment/dialog/listener/result/CommentRequestResultListener.kt
> +}
BindingAdapter에 있는 로직 중 Activity에 의존되는 로직들을 Activity class내부로 옮겼듯이 이제는 이런 결과에 따른 로직들도 Activity로 이동되어도 괜찮지 않을까라는 생각입니다.

이렇게 분리함으로써 Class들간의 역할이 잘 분리되어 Activity가 비대해지는 것을 막을 수 있지만 코드가 파편화된다는 생각도 듭니다.

2023-09-08 06:12 UTC, boogi-woogi commented on android/app/src/test/java/com/digginroom/digginroom/feature/room/customview/roominfoview/comment/CommentViewModelTest.kt
> +        assertEquals(commentCount - 1, actual.size)
expected도 존재하면 더욱 가독성이 좋은 테스트 코드가 될 것으로 예상합니다~

2023-09-08 06:12 UTC, boogi-woogi commented on android/app/src/test/java/com/digginroom/digginroom/feature/room/customview/roominfoview/comment/CommentViewModelTest.kt
> +        assertTrue(actual is CommentRequestState.Failed)
CommentRequestState.Failed가 어짜피 object 클래스이므로 다른 테스트 코드들과 같이 expected 변수를 CommentRequestState.Failed로 두고 assertEquals를 사용하면 더욱 일관성있는 테스트 코드가 되지 않을까요?

2023-09-08 07:36 UTC, whk06061 commented on android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roominfoview/comment/CommentViewModel.kt
> +
넵! ㅎㅎ 외부에서 liveData의 value 를 변경하기 위해 사용되는 함수 제외하고는 대입문을 바로 써주었습니다~!

2023-09-08 07:55 UTC, whk06061 commented on android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roominfoview/comment/dialog/listener/result/CommentRequestResultListener.kt
> +}
저도 동의합니다! Activity 의 역할인 로직들은 굳이 BindingAdapter 로 분리하지 않고, Activity 에 작성하는 것이 가독성을 높여주고 적절한 위치라고 생각합니다! 

이 부분은 별도로 이슈를 파서 한 번에 수정하겠습니다!

2023-09-08 08:04 UTC, whk06061 commented on android/app/src/main/java/com/digginroom/digginroom/feature/room/customview/roominfoview/comment/CommentViewModel.kt
> +    }
CommentRequstState 에 대한 처리를 완료했다는 의미로, `handleCommentRequestState` 라는 네이밍을 생각해보았는데, 이 네이밍은 어떤가요?!

2023-09-08 08:16 UTC, whk06061 commented on android/app/src/test/java/com/digginroom/digginroom/feature/room/customview/roominfoview/comment/CommentViewModelTest.kt
> +        assertTrue(actual is CommentRequestState.Failed)
CommentRequestState.Failed 가 실패 메시지를 담게 하기 위해서 data class 로 선언되어 있는 상태입니다!
따라서 class 타입으로 비교하기 위해 아래같이 적는 것은 어떻게 생각하시나요? 
```suggestion
      val actual = commentViewModel.commentRequestState.value ?: throw IllegalArgumentException()
        assertEquals(CommentRequestState.Failed::class, actual::class)
```

2023-09-08 08:20 UTC, boogi-woogi commented on android/app/src/test/java/com/digginroom/digginroom/feature/room/customview/roominfoview/comment/CommentViewModelTest.kt
> +        assertTrue(actual is CommentRequestState.Failed)
아 Failed를 object 클래스로 착각했습니다.  기존에 작성하신 테스트 코드로 사용하는게 더 좋아보입니다! 혼동을 드려서 죄송합니다ㅜㅜ

2023-09-08 08:23 UTC, whk06061 commented on android/app/src/test/java/com/digginroom/digginroom/feature/room/customview/roominfoview/comment/CommentViewModelTest.kt
> +        assertTrue(actual is CommentRequestState.Failed)
아닙니다!! ㅎㅎ 가독성 측면에서 고민이 됐었는데.. 기존 코드로 유지하겠습니다~!

2023-09-11 05:00 UTC, boogi-woogi approved these changes

2023-09-11 05:02 UTC, merged