feat: 카카오 소셜 로그인 기능을 구현한다.
woowacourse-teams/2023-diggin-room pull request #301
Opened 2023-09-14 07:39 UTC by kong-hana01

## 관련 이슈번호
- #294 

## 작업 사항
- 카카오 소셜 로그인 기능 구현
  - 소셜 로그인 기능 추상화
- Member 객체 내 nickname 필드 추가
 - nickname 컬럼을 추가하는 sql 문 작성

## 기타 사항
#### 1. 제 1회 MyJwkProvider 클래스명 공모전 개최
현재 `MyJwkProvider` 클래스의 적절한 이름이 생각나지 않아 일단 남겨뒀습니다.
여러분들의 의견 부탁드릴게요!

#### 2. 닉네임과 관련해서 알아두면 좋을 사항
- 소셜 로그인 시 `Service` 계층에서 `소셜 로그인 IdToken의 정보를 활용해 nickname을 생성자에 전달`
- 일반 로그인 시 기존 생성자를 수정하지 않고, `내부 필드에서 랜덤한 값으로 nickname 생성`
  - 게스트 로그인 개발 시 참고해주세요.

2023-09-15 06:25 UTC, 0chil requested changes
파워, 콩하나 OIDC 아주 잘 구현해주셨네요!
추상화를 잘 해주신 덕분에 다음 작업들이 수월할 것 같습니다 👍
고생많으셨어요~~ 몇가지 코멘트 남겼으니 확인부탁드립니다

2023-09-15 06:25 UTC, 0chil commented on backend/src/main/java/com/digginroom/digginroom/oauth/MyConfig.java
> +}
1. 전체적으로 My 라는 이름이 왜 붙게되는건가요?
2. `MyConfig` 이름에서 등록된 Bean들이 무엇인지를 유추하기가 어려워요.
3. `MyJwkProvider`를 Config 및 Bean으로 등록해 관리하는 이유가 있나요?

2023-09-15 06:25 UTC, 0chil commented on backend/src/main/java/com/digginroom/digginroom/oauth/MyJwkProviders.java
> +    }
어디서 많이 보던 구조네요 ㅎㅎ
RuntimeException은 빠뜨리신 것 같습니다!

2023-09-15 06:25 UTC, 0chil commented on backend/src/main/java/com/digginroom/digginroom/service/MemberService.java
> +                        new Member(kakaoUsername, Provider.KAKAO, name))
<img width="580" alt="image" src="https://github.com/woowacourse-teams/2023-diggin-room/assets/39221443/470ac2ec-c3c2-41f9-8c3f-269c6187660b">
<img width="600" alt="image" src="https://github.com/woowacourse-teams/2023-diggin-room/assets/39221443/dde3d57f-40cc-4729-9c0b-539bf743a7a0">

iss 를 활용해서 동적으로 구글, 카카오 모두 지원하도록 하면 어떨지 제안드려봅니다~

2023-09-15 06:25 UTC, 0chil commented on backend/src/main/java/com/digginroom/digginroom/service/MemberService.java
> +        String name = idToken.get("nickname").asString();
위 제안대로라면, 카카오, 구글등 Provider별로 다른 이름 필드를 적절하게 추상화할 수 있을 것 같습니다!
`Claim` 이라는 외부 의존성이 서비스 내에 존재할 필요도 사라지구요!
괜찮으시면 요 건은 제가 한번 해보겠습니다.

2023-09-15 12:13 UTC, Songusika requested changes
카카오 로그인 구현하시느라 고생하셨습니다!!
리뷰 남긴 부분은 같이 이야기 해보면 재미있을 것 같아용

2023-09-15 12:13 UTC, Songusika commented on backend/src/main/java/com/digginroom/digginroom/service/MemberService.java
> +        String name = idToken.get("name").asString();
이 부분에 대해서 어떻게 추상화할 수 있을지 고민해봤는데요
아래와 같은 구조는 어떤가요?

우리 서비스에서 회원에 필요한 정보를 담는 객체 일종의 DTO
```java
record UserInfo(String username, String nickname) {
}
```
각 Provider `UserInfoResponse`가 구현할 인터페이스
```java
public interface UserInfoResponse {
  public toUserInfo();
}
```
예를 들면 카카오 `UserInfoResponse` 는 아래와 같이 사용할 수 있어요.
```java
public class KaKaoUserInfoResponse implements UserInfoResponse {
  
  private final Map<String, Claim> idToken;

  public KaKaoUserInfoResponse(final Map<String, Claim> idToken) {
     this.idToken = idToken;
  }
  
  @Override
  public UserInfo toUserInfo() {
     // 각 필드를 Provider 에 맞게 넘겨주면 됩니다.
     return new UserInfo(idToken.get("sub").asString(), idToken.get("nickname").asString());
  }
}
```

이후 해당 객체를 넘겨주는 `Functional Interface`를 enum에 정의했습니다.
```java
public enum Provider {

    ..다른 Provider들...
    KAKAO(KaKaoUserInfoResponse::new);

    private Function<Map<String, Claim>, UserInfoResponse> expression;

    Provider(final Function<Map<String, Claim>, UserInfoResponse> expression) {
        this.expression = expression;
    }

    public UserInfoResponse getProviderUserInfoResponse(final Map<String, Claim> idToken) {
        return expression.apply(idToken);
    }
}
```
그럼 아래와 같이 `IdTokenResolver`에서 바로 회원가입에 필요한 `UserInfo` 를 넘길 수 있어요!
```java
public class IdTokenResolver {

    private final MyJwkProviders myJwkProviders;

    public UserInfo resolve(final String idToken, final Provider provider) {
        ... 생략
        return provider.
               getProviderUserInfoResponse(verifier.verify(idToken).getClaims())
               .toUserInfo();
         ... 생략
```

`MemberService` 에서는
```java
    public MemberLoginResponse loginMember(final KakaoOAuthRequest request, final Provider provider) {
        UserInfo userInfo = idTokenResolver.resolve(request.idToken(), provider);
        String username =userInfo.name();
        String name = userInfo.nickname();

        Member member = memberRepository.findMemberByUsername(username)
                .orElseGet(() -> memberRepository.save(
                        new Member(username, provider name))
                );

        return MemberLoginResponse.of(member);
    }
```
단 위의 조건은 컨트롤러에서 `Provider` 를 인자로 넘겨주도록 리팩터링 했다는 전제입니다.
다른 방식 더 좋은 방식이 있다면 그걸 써도 좋아요 😙

2023-09-17 10:02 UTC, Songusika commented on backend/src/main/java/com/digginroom/digginroom/service/MemberService.java
> +        String name = idToken.get("name").asString();
이 부분은 땡칠이 다음 PR에 반영한다고 하셔서 고려안하셔도 될 것 같습니다!!

2023-09-18 11:17 UTC, kong-hana01 commented on backend/src/main/java/com/digginroom/digginroom/domain/member/Member.java
> +        this.nickname = "user-" + UUID.randomUUID().toString().split("-")[0];
좋은 의견 감사해용

2023-09-18 11:37 UTC, kong-hana01 commented on backend/src/main/java/com/digginroom/digginroom/oauth/MyJwkProviders.java
> +    }
매의 눈 👍

2023-09-18 11:46 UTC, kong-hana01 commented on backend/src/main/java/com/digginroom/digginroom/oauth/MyJwkProvider.java
> +public record MyJwkProvider(JwkProvider jwkProvider, Provider provider) {
인텔리제이에서 추천해줘서 위와 같이 구현을 했었습니다.
그런데 다시 이야기를 나눠보니 현재 저희 코드에서는 `DTO`에서만 record를 사용하고 있습니다.
따라서 이 클래스 또한 dto로 오해의 소지가 있을 것 같아서 class로 변경했습니다!

2023-09-18 12:11 UTC, kong-hana01 commented on backend/src/main/java/com/digginroom/digginroom/domain/member/Member.java
> +        this.nickname = nickname;
인정합니다~~
한번 이야기 나눠보시죠!

2023-09-18 12:11 UTC, kong-hana01 commented on backend/src/main/java/com/digginroom/digginroom/oauth/MyJwkProvider.java
> +    public boolean support(Provider provider) {
매의눈

2023-09-18 12:11 UTC, kong-hana01 commented on backend/src/main/java/com/digginroom/digginroom/oauth/MyJwkProviders.java
> +    public JwkProvider getJwkProvider(Provider provider) {
솔의눈

2023-09-18 12:13 UTC, 0chil approved these changes
LGBT 🏳️‍🌈

2023-09-19 05:09 UTC, Songusika approved these changes
👍👍

2023-09-19 05:10 UTC, merged