refactor: DTO 패키지 이동 및 각 서비스간 의존을 제거한다.
woowacourse-teams/2023-diggin-room pull request #340
Opened 2023-10-04 11:48 UTC by Songusika

## 관련 이슈번호
- #331 

## 작업 사항
- DTO 패키지를 컨트롤러 패키지에서 서비스 패키지로 이동
- 서비스에서 다른 서비스를 의존하는 부분 제거
  - `CommentController -> RoomService -> CommentService` 의존 `CommentController -> CommentService` 구조로 변경
- 댓글 수정/삭제시 요청한 룸과 같은 룸인지 검증 하는 로직 제거 

## 기타 사항
- `getXXById` 메서드 네이밍
  - 현재 Id를 통해 엔티티를 가져올 때 예외를 레포지터리에서 터트리도록 `getXXById` 메서드를 각 레포지터리에 구현하였습니다.
  - `getById`라는 네이밍도 있지만 이미 `JpaRepository`에 해당 메서드가 구현되어 있어서 명시적으로 도메인 이름을 붙여주었습니다. 
- 댓글 수정/삭제 API 변경 필요
  - 현재 댓글은 룸ID 과 상관없이 ID가 올라갑니다. (룸ID 별로 댓글 테이블이 있는 형태가 아닌 하나의 댓글 테이블로 존재하기 때문)
  - 따라서 룸을 수정/삭제할 때 다른 룸의 댓글일 경우가 존재하지 않습니다.
    - ex) 1번 룸의 10번 댓글 - 2번 룸의 10번 댓글이 존재할 수 없습니다.
  - 따라서 기존 댓글을 수정/삭제 시 룸 ID가 필요가 없어졌기 때문에 API 수정이 필요해 보입니다.  
     - 단, 의미적으로는"`/rooms/{roomId}/comments/{commentId}` _라는 API가 룸에 종속된 댓글이다_ "가 더 맞는것 같습니다.
     - 테이블을 수정하는 방법 혹은 API 를 회의를 거쳐 수정이 필요합니다.

2023-10-06 08:29 UTC, 0chil approved these changes
대대적인 수정 고생 많으셨습니다!
적응이 필요하겠지만 우선은 기존보다 좋아보이네요

2023-10-06 08:29 UTC, 0chil commented on backend/src/test/java/com/digginroom/digginroom/controller/CommentControllerTest.java
> +        System.out.println("쿠키" + cookie);
일부러 남긴 걸까요? 😂

2023-10-06 11:15 UTC, Songusika commented on backend/src/test/java/com/digginroom/digginroom/controller/CommentControllerTest.java
> +        System.out.println("쿠키" + cookie);
실수로 파라미터 순서가 잘못되어서 로그인이 안되던 문제인제 당시에 발견을 하지 못해가지고 sout .. 하하
삭제했습니다.

2023-10-06 12:53 UTC, thdwoqor requested changes
잘 분리한거같아요
Member가 가지고있는 ScrapRooms, DislikeRooms, MemberGenres
요런것들도 분리 예정일까요?

2023-10-06 12:53 UTC, thdwoqor commented on backend/src/main/java/com/digginroom/digginroom/service/CommentService.java
> +        Member member = memberRepository.getMemberById(memberId);
생각해보니 getMemberById 가 필요없을거같아요
@Auth를 통해서 검증된 memberId를 가져오는데 그러면 comment에서 isOwner에서 memberId로 비교하면 되지않을까요?

2023-10-06 12:53 UTC, thdwoqor commented on backend/src/main/java/com/digginroom/digginroom/service/CommentService.java
> +        Member member = memberRepository.getMemberById(memberId);
위 리뷰와 동일하고 그렇게된다면 MemberRepository도 필요없을것같습니다

2023-10-10 01:40 UTC, Songusika commented on backend/src/main/java/com/digginroom/digginroom/service/CommentService.java
> +        Member member = memberRepository.getMemberById(memberId);
꼼꼼한 검증 👍👍👍

2023-10-10 01:47 UTC, thdwoqor approved these changes

2023-10-10 01:49 UTC, merged

2023-10-15 08:30 UTC, kong-hana01 commented on backend/src/main/java/com/digginroom/digginroom/service/CommentService.java
> +        Member member = memberRepository.getMemberById(memberId);
추후 댓글 기능에서 member 객체를 그대로 가지고 있는 것이 아닌,
id를 조회하도록 변경할 예정이니 그때 새로운 pr을 열어서 반영하도록 하겠습니다!