feat: 피드백 창구를 개설한다
woowacourse-teams/2023-diggin-room pull request #344
Opened 2023-10-05 07:56 UTC by 0chil

## 관련 이슈번호
- #343 

## 작업 사항
- 피드백 받기 위한 API 개설
  - 피드백 내용, 피드백 작성자 기록

## 기타 사항
- 기존 패키지와 별도로 생성
  - 다른 기능 개발이나 리팩터링에 영향을 주거나 받지 않는다.

2023-10-05 08:02 UTC, 0chil commented on backend/src/main/java/com/digginroom/digginroom/feedback/controller/FeedbackController.java
> +    public ResponseEntity<Void> takeFeedbackFrom(Member member, final @RequestBody FeedbackRequest feedback) {
우선 인증이 필요할까 싶어 Member를 달아놓았습니다.
내일 상의후 제거될 수 있습니다.

2023-10-05 08:23 UTC, Songusika requested changes
땡칠 피드백 창구 구현하느라 고생했어요!!
저희 피드백 정보에 유저를 넣을지 같이 고민해보면 좋을 것 같아서 RC 남겨놓았습니다!

2023-10-05 08:23 UTC, Songusika commented on backend/src/main/java/com/digginroom/digginroom/feedback/domain/Feedback.java
> +    public Feedback(String content) {
`final` 도망갔어요! 🏃‍♂️

2023-10-05 08:23 UTC, Songusika commented on backend/src/main/java/com/digginroom/digginroom/feedback/domain/Feedback.java
> +}
저번에 파워가 만든 `BaseEntity`를 상속하면 좋을 것 같아요
추가로 어떤 유저가 남긴 피드백인지 알면 좋을 것 같아요. (이상한 유저 방지 차원에서!)

2023-10-05 08:23 UTC, Songusika commented on backend/src/test/java/com/digginroom/digginroom/feedback/FeedbackServiceTest.java
> +@DataJpaTest
저희 문자 길이에 맞게 선언 순서 조절하면 어떨까요?

2023-10-05 08:23 UTC, Songusika commented on backend/src/main/java/com/digginroom/digginroom/feedback/dto/FeedbackResponse.java
> +    public static FeedbackResponse of(Feedback feedback) {
퐈이날! 😊

2023-10-05 08:23 UTC, Songusika commented on backend/src/test/java/com/digginroom/digginroom/feedback/FeedbackServiceTest.java
> +        String content = "피드백 창구를 빨랑 만들어주세요";
스스로 빨랑 만드는 땡칠 그는 도덕책...👍

2023-10-05 08:23 UTC, Songusika commented on backend/src/main/java/com/digginroom/digginroom/feedback/controller/FeedbackController.java
> +    public ResponseEntity<Void> takeFeedbackFrom(Member member, final @RequestBody FeedbackRequest feedback) {
저희 `@Auth` 를 통해서 `memberId`를 받지 않는 이유는  사용하지 않기 때문인가요??

2023-10-05 08:24 UTC, Songusika commented on backend/src/main/java/com/digginroom/digginroom/feedback/controller/FeedbackController.java
> +    public ResponseEntity<Void> takeFeedbackFrom(Member member, final @RequestBody FeedbackRequest feedback) {
스프링에서 Member 객체를 어떻게 넣어주는거지..? 고민을 한참했습니다 ㅋㅋㅋ

2023-10-05 09:55 UTC, 0chil commented on backend/src/main/java/com/digginroom/digginroom/feedback/controller/FeedbackController.java
> +    public ResponseEntity<Void> takeFeedbackFrom(Member member, final @RequestBody FeedbackRequest feedback) {
착오가 있었습니다 😱 반영 완료입니다

2023-10-05 09:58 UTC, 0chil commented on backend/src/main/java/com/digginroom/digginroom/feedback/domain/Feedback.java
> +    public Feedback(String content) {
반영완료!

2023-10-05 09:58 UTC, 0chil commented on backend/src/main/java/com/digginroom/digginroom/feedback/domain/Feedback.java
> +}
그 부분 해서 올려놨는데 그 사이에 리뷰를 시작하셨군여 ㅎㅎ
추가 커멘트는 반영해보겠습니다.

2023-10-05 10:01 UTC, 0chil commented on backend/src/main/java/com/digginroom/digginroom/feedback/dto/FeedbackResponse.java
> +    public static FeedbackResponse of(Feedback feedback) {
완료!

2023-10-05 10:01 UTC, 0chil commented on backend/src/test/java/com/digginroom/digginroom/feedback/FeedbackServiceTest.java
> +@DataJpaTest
깜빡했네요! 완료!

2023-10-06 05:18 UTC, Songusika approved these changes
피드백 창구 만드시느라 고생하셨습니다! LGTM🚀

2023-10-06 13:22 UTC, thdwoqor requested changes
고생하셨습니다.

2023-10-06 13:22 UTC, thdwoqor commented on backend/src/main/java/com/digginroom/digginroom/feedback/domain/Feedback.java
> +    private Member writer;
FeadBack이 Member 도메인을 가지고있을 필요가 없을것같다는 생각이들어요
Id값만 가지고있어도 되지않나요?

2023-10-06 13:22 UTC, thdwoqor commented on backend/src/main/java/com/digginroom/digginroom/feedback/FeedbackService.java
> +    private final MemberRepository memberRepository;
도메인 리뷰와같이 Member 도메인이아닌 Id를 가지고있으면 MemberRepository가 필요없을것같네요

2023-10-06 14:37 UTC, 0chil commented on backend/src/main/java/com/digginroom/digginroom/feedback/domain/Feedback.java
> +    private Member writer;
당연히 Id 값만 가지도록 구현도 가능하죠!
근데 그 전에 파워가 왜 Feedback 객체가 Member 도메인을 가질 필요 없다고 생각했는지 듣고 싶어요.

저는 조회할 때도, 유지보수할 때도 편하기 때문에 Member 도메인을 가지는 편이 낫다고 생각해서 애렇게 구현했거든요.

아직 Feedback이 작성자를 가지고 무슨 일을 할지 잘 모르잖아요.
Member 객체를 DB 조회에 의존하지 않는 유연한 상태로 두어야 변화에 대응하기가 편하지 않을까요?

뚜렷한 이점이 있는 것도 아닌데 유연함과 편리함을 버릴 필요가 있을까요?
우리가 ORM을 왜 쓰고있을까요?

2023-10-07 06:48 UTC, thdwoqor commented on backend/src/main/java/com/digginroom/digginroom/feedback/domain/Feedback.java
> +    private Member writer;
Room Comment와 비슷한 상황같은데
Member와 Feedback 둘다 전혀 다른 애그리거트(생성주기)를 가지고있고 Feedback이 Member 객체를 가지고 무엇을 할수있을까요? 미래를 생각해도 잘떠오르지않고 실제로 사용하는 경우가 생겼을때 Member 객체로 만들어도 되지않나요?
어차피 DB 변경사항은 없을거같아요 
지금 Member 객체를 만들기위해서 Member를 조회하고 패키지를 참고하는 과정이 "뚜렷한 이점이 없고 아닌데 불편함" 아닐까요?

2023-10-08 07:01 UTC, kong-hana01 reviewed
안녕하세요 땡칠
아주 야물딱지게 잘 구현해주셨네용 ㅎㅎ
몇 가지 코멘트 남겼으니 확인부탁드릴게용~~

고생하셨고 화요일에 봅시다 ㅎㅎㅎㅎ

2023-10-08 07:01 UTC, kong-hana01 commented on backend/src/main/java/com/digginroom/digginroom/feedback/controller/FeedbackController.java
> +    }
이건 다른 분들의 의견도 궁금하네요 ㅎㅎ

2023-10-10 01:46 UTC, 0chil commented on backend/src/main/java/com/digginroom/digginroom/feedback/FeedbackService.java
> +    private final MemberRepository memberRepository;
쿼리 개수 측면에서는 Lazy Load가 있어서 성능 상 이점은 없을 것 같아요.
이 부분 명확히 답을 내리기는 어려워서 다수결에 따르겠습니다.

2023-10-10 02:42 UTC, 0chil commented on backend/src/main/java/com/digginroom/digginroom/feedback/controller/FeedbackController.java
> +    }
요거 저도 필요하다고 생각하는데요, 논의해보고 PR에서 해보도록 하겠습니다.

2023-10-10 02:42 UTC, 0chil commented on backend/src/main/resources/db/migration/V6.2__create_table_feedback.sql
> +    id         bigint auto_increment primary key,
완료!

2023-10-10 02:43 UTC, 0chil commented on backend/src/main/resources/db/migration/V6.2__create_table_feedback.sql
> +create table feedback
if not exists - table 존재 유무만 확인하므로 
테이블이 이미 있는 경우 오류 없이 넘어가버릴 가능성이 있다.
결론적으로 스키마가 잘 적용되지 않았음에도 정상 상태라고 판명될 가능성이 있다.

2023-10-10 02:53 UTC, thdwoqor approved these changes

2023-10-10 02:54 UTC, merged