fix: docker volumes이 삭제되지 않는 문제 해결
woowacourse-teams/2023-diggin-room pull request #372
Opened 2023-10-13 12:54 UTC by thdwoqor

## 관련 이슈번호
<br/>371

## 작업 사항
<br/>

## 기타 사항
<br/>

2023-10-13 14:12 UTC, 0chil requested changes
~~[다음 구문](https://github.com/woowacourse-teams/2023-diggin-room/blob/0ef6b8b746f3a2225388e7dee5799ea119d320a6/.github/workflows/ci-dev-db.yml#L39C9-L41C21)에서, `--rm` 옵션으로 인해 Docker volume이 남지 않습니다.
```yaml
run: |
  sudo docker run --rm --name $MYSQL_CONTAINER_NAME -e MYSQL_ROOT_PASSWORD=root -P \
  ${{ env.DOCKER_HEALTHCHECK_OPTIONS }} \
  -d mysql:8.0
```
~~
~~참고:  [Docker `run --rm` Docs](https://docs.docker.com/engine/reference/run/#clean-up---rm)~~
라고 할뻔;;

왜 제거가 안돼죠?

2023-10-13 14:14 UTC, 0chil commented on .github/workflows/ci-dev-db.yml
> +          --where="1 limit 100" \
이거 조사만 해두고 적용 안했던 건데, 너무 적절합니다~!
[당시 조사했던 Stackoverflow 글 공유합니다~](https://stackoverflow.com/questions/135835/limiting-the-number-of-records-from-mysqldump)

2023-10-13 14:21 UTC, thdwoqor commented
@0chil 
도커 공식문서에서는 못찾겠는데 다른곳 이슈보면 명시적인 이름으로 컨테이너 실행했을때 volume은 안지워주는거같네요
https://github.com/moby/moby/issues/23023

2023-10-13 14:25 UTC, 0chil commented
> @0chil 
> 
> 도커 공식문서에서는 못찾겠는데 다른곳 이슈보면 명시적인 이름으로 컨테이너 실행했을때 volume은 안지워주는거같네요
> 
> https://github.com/moby/moby/issues/23023

아 그런거였군여~ 조사 감사합니다!

하는김에 --rm도 제거할까여?

2023-10-13 15:16 UTC, 0chil approved these changes

2023-10-14 12:10 UTC, kong-hana01 approved these changes
> 도커 공식문서에서는 못찾겠는데 다른곳 이슈보면 명시적인 이름으로 컨테이너 실행했을때 volume은 안지워주는거같네요

도커 공식문서에서 볼륨 삭제하는 부분에 관련 내용이 있네요!
![image](https://github.com/woowacourse-teams/2023-diggin-room/assets/79015120/fa2d8b4a-a15f-4e20-aff5-4c16ceddfe5a)

> This command removes the container and any volumes associated with it. Note that if a volume was specified with a name, it will not be removed.

고생하셨습니다 파워~

2023-10-16 04:51 UTC, Songusika approved these changes
고생하셨습니다 파워.

`--rm` 옵션은 컨테이너를 자동으로 삭제할 때 사용되지만, 연결된 볼륨(volume)은 자동으로 삭제하지 않는 이유가 아래와 같다고 하네요.

> Docker 컨테이너와 볼륨은 별개의 리소스로 관리되기 때문에, 컨테이너를 삭제하더라도 볼륨은 남아있습니다. 이는 사용자가 실수로 중요한 데이터를 담고 있는 볼륨을 삭제하는 것을 방지하기 위한 설계입니다

이 부분을 조사하면서 찾은 것인데 지금은 컨테이너와 볼륨을 한번에 지워야 하기 때문에 89번째 명령어를 사용해야하지만 
`docker volume prune` 명령어는 사용하지 않는 볼륨을 삭제한다고 하네요

2023-10-16 04:51 UTC, merged