Feature/384
woowacourse-teams/2023-diggin-room pull request #408
Opened 2023-10-18 17:26 UTC by kong-hana01

## 관련 이슈번호
- #384 

## 작업 사항
### 댓글 무한 스크롤 기능 구현
- lastCommentId와 size를 전달받아 `lastCommentId 이전에 작성된 댓글`들을 `최대 size 개수 만큼` 클라이언트에게 전달합니다.
  - 이때 최대 size 개수보다 lastCommentId 이전에 작성된 댓글이 더 적은 경우에는 남은 댓글의 개수만큼만 전달합니다.
  - lastCommentId는 null이 전달될 수 있습니다. 
    - null이 전달되는 경우에는 service에서 Long.MAX_VALUE로 바꿔서 레포지토리에 전달하고 있어요. 
    - `하위 호환성을 확보`하기 위함 + `클라이언트 측에서 첫 요청을 보낼 때 최신 댓글 id를 몰라도 된다는 점`을 위해 이렇게 구현했습니다.
  - size는 null이 전달될 수 있습니다.
    - null이 전달되는 경우에는 `기본값 10`으로 매핑됩니다.
    - size가 0 이하인 경우에는 `Pagable 객체에서 생성 시 예외`를 던지기 때문에 서비스에서 이를 검증하고 있습니다.

## 기타 사항
- 노션에 댓글 무한스크롤 기능관련 api 명세 작성해놨으니 확인 부탁드릴게요!

2023-10-19 08:40 UTC, 0chil approved these changes
고생하셨습니다 (구두 질답 진행)

2023-10-24 02:03 UTC, thdwoqor requested changes
[범위](https://github.com/woowacourse-teams/2023-diggin-room/pull/408/files/be4e6aecc3c3dbb03b99a9842205d9281037ec70..627ed8459bd24a970718e3c49db2e713e070cc81#diff-e122667df31aa3a31eee0911fd37d1066827d883fc4c43d6d1831383d0a0bfb3R23-R34)

2023-10-24 02:03 UTC, thdwoqor commented on backend/src/main/java/com/digginroom/digginroom/repository/CommentRepository.java
> +    );
```
Hibernate: 
    select
        c1_0.id,
        c1_0.comment,
        c1_0.created_at,
        m1_0.id,
        m1_0.created_at,
        m1_0.has_favorite,
        m1_0.nickname,
        m1_0.password,
        m1_0.provider,
        m1_0.updated_at,
        m1_0.username,
        c1_0.room_id,
        c1_0.updated_at 
    from
        comment c1_0 
    join
        member m1_0 
            on m1_0.id=c1_0.member_id 
    where
        c1_0.room_id=? 
        and c1_0.id<? 
    order by
        c1_0.id desc offset ? rows fetch first ? rows only
```

커서방식으로 구현하시려고한거같은데
실제쿼리는 offset을 사용하네요

2023-11-06 04:29 UTC, Songusika commented on backend/src/main/java/com/digginroom/digginroom/repository/CommentRepository.java
> +    );
`DEFAULT_PAGE_SIZE` 를 서비스단에서 0으로 고정하였습니다!
추가적으로 Page 객체가 아닌, Slice 객체를 리턴하도록하여 count 쿼리를 발생을 줄였습니다

2023-11-06 06:26 UTC, thdwoqor approved these changes

2023-11-06 10:12 UTC, merged