댓글 무한 스크롤을 구현한다
woowacourse-teams/2023-diggin-room pull request #419
Opened 2023-10-25 05:04 UTC by whk06061

## 관련 이슈번호
- #385 

## 작업 사항
- 마지막 댓글 아이디와 요청 사이즈를 토대로 리사이클러뷰의 하단에 닿을 때 마다 서버에 댓글을 요청합니다. 
- 정상 작동 확인 후 머지하겠습니다 ! 일단 구조적으로 개선할 점이 있는지 리뷰 부탁드려요~!

## 기타 사항
- RecyclerView 의 ScrollListener 에서 쓰인 `canScrollVertically(1)` 함수는 수직 스크롤 최하단에 도달했는지를 반환하는 함수입니다.

2023-11-07 07:42 UTC, DYGames requested changes
오프라인 리뷰 완료했습니다.
1. 뷰모델 함수 분리
2. canScrollVertically() 인자 매직넘버

2023-11-07 08:05 UTC, boogi-woogi commented on android/app/src/main/java/com/digginroom/digginroom/feature/room/comment/uistate/CommentResponseUiState.kt
> +            override val comments: List<CommentItem> = emptyList()
default value로 모두 emptyList를 주고 있는 이유가 무엇인가요?

2023-11-07 08:07 UTC, boogi-woogi commented on android/app/src/main/java/com/digginroom/digginroom/feature/room/comment/adapter/CommentAdapter.kt
>          }
ItemType을 Enum으로 만들고 enum의 factory method로 position을 받고 그에 해당하는 Item Type의 ordinal을 뱉는것도 나쁘지 않아 보입니다~

2023-11-07 08:09 UTC, boogi-woogi commented on android/app/src/main/java/com/digginroom/digginroom/feature/room/comment/adapter/CommentViewType.kt
> +}
Enum으로 만들지 않은 이유가 있나요??

2023-11-07 08:11 UTC, boogi-woogi requested changes
자그마한 궁금증이 있는데 확인해주시면 감사하겠씁니다~

2023-11-07 12:34 UTC, Songusika commented on android/app/src/main/java/com/digginroom/digginroom/feature/room/comment/adapter/CommentViewType.kt
> +}
저도 궁금하네요

2023-11-07 13:51 UTC, whk06061 commented on android/app/src/main/java/com/digginroom/digginroom/feature/room/comment/adapter/CommentAdapter.kt
>          }
오 좋은데요?! 반영할게요 !

2023-11-07 13:57 UTC, whk06061 commented on android/app/src/main/java/com/digginroom/digginroom/feature/room/comment/adapter/CommentViewType.kt
> +}
Enum 을 써서 when 분기문 처리를 빠짐없이 해야되는 상황이 없기 때문에 굳이 Enum 클래스의 필요성을 느끼지 못했었어요 
그치만 위에서 우기가 달아준 [코멘트](https://github.com/woowacourse-teams/2023-diggin-room/pull/419#discussion_r1384521417)를 보니 Enum Class 의 사용이 적합할 것 같습니다 👍

2023-11-07 14:27 UTC, whk06061 commented on android/app/src/main/java/com/digginroom/digginroom/feature/room/comment/adapter/CommentViewType.kt
> +}
아앗 Enum Class 의 사용이 적당할거같아요!! 처음엔 Enum 에 대한 when 분기처리가 필요한 경우가 없어서 굳이 안썼는데 지금 생각해보니 굳이 Enum을 안쓰는게 더 이상하네용

2023-11-07 14:34 UTC, whk06061 commented on android/app/src/main/java/com/digginroom/digginroom/feature/room/comment/adapter/CommentAdapter.kt
>          }
Loading 과 CommentModel 의 클래스 유형이 다르기 때문에 ItemType 은 현재 sealed class 로 구현한 상태입니다!
따라서 companion object  를 사용해서 팩토리 메소드로 구현하는게 나을 것 같은데 어떤가요?

2023-11-07 14:37 UTC, DYGames commented on android/app/src/main/java/com/digginroom/digginroom/feature/room/comment/adapter/CommentAdapter.kt
>          }
좀 더 원론적으로 , CommentItem이랑 CommentViewType의 역할 차이가 있을까요? 
애초에 UI Model에 State가 들어간게 어색하지 않나요?

2023-11-07 14:46 UTC, whk06061 commented on android/app/src/main/java/com/digginroom/digginroom/feature/room/comment/adapter/CommentAdapter.kt
>          }
State 가 어떤 의미일까요! ViewType 을 의미하는건가용? 설명해주세요 😲

2023-11-07 15:13 UTC, DYGames commented on android/app/src/main/java/com/digginroom/digginroom/feature/room/comment/adapter/CommentAdapter.kt
>          }
아 CommentItem이라는 UI Model은 UI에 표시되는 내용을 담고있는 "모델" 클래스이고, 어떻게 표시될지 분기처리되는 상태는 UI State 클래스들이 갖고 있어야겠죠

2023-11-08 05:53 UTC, boogi-woogi approved these changes
고생하셨습니다~

2023-11-08 05:53 UTC, boogi-woogi commented on android/app/src/main/res/layout/dialog_comment_bottom_placed_item_layout.xml
> +            type="com.digginroom.digginroom.feature.room.comment.uistate.CommentUiState.CommentModel" />
변수인데 동사처럼 느껴져서 바꿔주시면 감사하겠습니다~

2023-11-08 06:21 UTC, merged