chore: actuator 적용
woowacourse-teams/2023-diggin-room pull request #421
Opened 2023-10-25 08:24 UTC by kong-hana01

## 관련 이슈번호
- #420 

## 작업 사항
- 서버 헬스 체크를 위한 actuator 적용

## 기타 사항

2023-10-25 08:27 UTC, kong-hana01 commented on backend/src/main/resources/application.yml
> +    version: '1.0.0'
해당 version을 통해 앞으로 서버의 버저닝을 관리하고자 합니다.

2023-10-25 08:27 UTC, kong-hana01 commented on backend/src/main/resources/application.yml
> +        include: info
url을 통해 `health/info`로 요청이 들어오면 서버의 상태를 확인할 수 있도록 엔드포인트를 열어둡니다.

2023-10-25 08:54 UTC, Songusika requested changes
고생했습니다!
보안 관련된 이슈가 있을 것 같아서 RC 남겼는데 이야기 해보고 반영했으면 좋겠습니다!

2023-10-25 08:54 UTC, Songusika commented on backend/src/main/resources/application.yml
> +    version: '1.0.0'
각각 어느 시점에 어느 버전을 올려야하는지 기준이 필요해보여요
`Major`
`Minor`
`Patch`

2023-10-25 08:54 UTC, Songusika commented on backend/src/main/resources/application.yml
> +        include: info
<img width="687" alt="image" src="https://github.com/woowacourse-teams/2023-diggin-room/assets/74398096/17186347-6fc7-49d7-97eb-45ae95566c04">

<img width="720" alt="image" src="https://github.com/woowacourse-teams/2023-diggin-room/assets/74398096/7dff199d-83ec-4854-9f66-3ab9933db4df">
이 부분은 로컬에서만 발생하는 이슈인가요..?

2023-10-25 08:54 UTC, Songusika commented on backend/src/main/resources/application.yml
> +        include: info
```suggestion
  endpoints:
    web:
      exposure:
        include: info
      base-path: /check
  server:
    port: 8888
```

`port` 와 `base-path` 는 예시로 넣었습니다.
위와 같이 포트와 base-path 를 기본 설정 말고 자체적으로 설정해서 적용하면 어떨까요?
해당 값들은 `Secret` 에 등록하면 더 좋을 것 같구요!

추가적으로 `Spring Actuator`를 사용하는 이유가 아래와 같다면
_"무중단 CD 과정에서 Blue/Green 을 구분"_

굳이 다른 이에게 노출될 이유가 없을 것 같아요!

이미 읽으셨을 수 도 있지만 아래 포스트 내용이 좋아서 공유해드립니다~
[Actuator 안전하게 사용하기](https://techblog.woowahan.com/9232/)

2023-10-25 08:54 UTC, Songusika commented on backend/src/main/resources/application.yml
> +        include: info
아 기본 `base-path` 가 `/actuator` 였군요!

2023-10-25 08:59 UTC, kong-hana01 commented on backend/src/main/resources/application.yml
> +    version: '1.0.0'
Major는 안드와 함께 가고, 
Minor는 api 변경,
Patch는 기능 업그레이드

로 진행하는거 어떤가요?

2023-10-25 08:59 UTC, kong-hana01 commented on backend/src/main/resources/application.yml
> +        include: info
좋은 의견입니다!

2023-10-25 08:59 UTC, kong-hana01 commented on backend/src/main/resources/application.yml
> +        include: info
아 ㅋㅁㅋㅋㅋㅋ 죄송합니다
내용 수정할게요

2023-10-25 09:26 UTC, Songusika commented on backend/src/main/resources/application.yml
> +    version: '1.0.0'
굿굿 Major 는 안드로이드와 함께 가면 구분하기 쉬울 것 같네용 👍🏻👍🏻

Major 는 안드에 맞춰서 새로운 기능을 하는 API 추가
Minor 는 기존 기능의 API 명세 변경
Path 는 API 에 영향이 없는 자잘한 개선 사항 반영 

로 이해하면 좋을까요?

2023-10-25 10:49 UTC, thdwoqor commented on backend/src/main/resources/application.yml
> +        include: info
"Actuator를 사용할때 조심해야한다." 라는 부분에 동의를 해서 `include: info` 와 같이 info만 허용했고
info 중에서도 version 이라는 정보만 노출되어있기때문에 Secret이나 path를 변경해주는 작업을 추가적으로 해줄 필요가 없다고 판단했는데 version이라는 정보자체도 숨기고싶으신건가요?


<img width="141" alt="image" src="https://github.com/woowacourse-teams/2023-diggin-room/assets/83541246/cfe34956-7f75-4d76-b97d-796a0d74d654">


<img width="357" alt="image" src="https://github.com/woowacourse-teams/2023-diggin-room/assets/83541246/f99bd43a-bd82-46be-add5-34a730446707">

2023-10-26 00:41 UTC, Songusika commented on backend/src/main/resources/application.yml
> +        include: info
버전 정보 자체라기 보다는 저희 서버의 메타데이터 자체를 숨기면 어떨까합니다.
현재는 `info` 에 서버 버전만 나오고 있기 떄문에 큰 문제는 없습니다.
하지만 이런 메타데이터는 다른 사용자들에게 노출될 이유가 없다고 생각해요

추후에 `info` 를 통해서 보여주고 싶은 정보가 추가되었을 경우 설정을 추가하는 것보다
지금 큰 작업의 변동 사항이 없을 때 미리 추가하는게 크루들간 컨텍스트 공유가 더 원활하지 않을까 합니다.

2023-10-26 10:04 UTC, kong-hana01 commented on backend/src/main/resources/application.yml
> +        include: info
좋습니다. 
```
server:
   port: 8888
```
이 부분도 다른 사용자들에게 감추려고 지정하는 걸까요?

현재 여러 포트 위에서 서버가 돌아가고 있는 것을 가정하고 있기 때문에 이 부분은 제외하는건 어떨까요?
경로만 secret으로 설정해도 충분히 안전할 것이라 생각해요!

2023-10-26 10:34 UTC, kong-hana01 commented on backend/src/main/resources/application.yml
> +    version: '1.0.0'
노션에 올렸습니다.

2023-10-26 10:51 UTC, kong-hana01 commented on backend/src/main/resources/application.yml
> +        include: info
경로 secert으로 설정하니까 빌드할 때 바로 터지네요.
직접 url을 명시해주는 방향으로 수정했습니다.

2023-10-26 11:01 UTC, Songusika approved these changes

2023-10-26 11:05 UTC, 0chil approved these changes
우선 여기까지 하고, 하위 호환 배포 자동화 작업을 하면서 문제있으면 더 개선해봅시다!
(엔드포인트, management.endpoints.enabled-by-default 같은 것)
고생 많으셨습니다.

2023-10-26 11:06 UTC, merged