feat: PasswordEncoder 변경 및 DirtiesContext 삭제
woowacourse-teams/2023-diggin-room pull request #429
Opened 2023-11-08 12:24 UTC by thdwoqor

# 관련 이슈번호
- #428 

# 작업 사항
## PasswordEncoder 변경
PasswordEncoder를 도메인 서비스로 보고 변경 했습니다.
[참고](https://incheol-jung.gitbook.io/docs/study/ddd-start/7#undefined-2)

현재 PasswordEncoder가 도메인안에있어서 Spring Security로 PasswordEncoder가 변경되는 상황에서 유연하게 대처하기 힘들기 때문에 수정해봤습니다.
[이런느낌](https://github.com/woowacourse/service-apply/blob/master/src/main/kotlin/apply/domain/applicationform/ApplicationForm.kt)

## DirtiesContext 삭제
Controller에서 DirtiesContext 대신 매 테스트마다 Database만 TRUNCATE 하도록 변경했습니다.
16초->6초 개선
![image](https://github.com/woowacourse-teams/2023-diggin-room/assets/83541246/e4be3474-e7a6-40ae-a860-a9ceea118513)
![image](https://github.com/woowacourse-teams/2023-diggin-room/assets/83541246/71af6c12-c0e0-4000-8cbe-117bded5ad2b)

## 논의 해보고싶은거
### data.sql 이거 필요할까요?
테스트는 data.sql 없이 테스트 가능한 상황이에요
만약에 data.sql이 필요하다면 로컬에서 테스트해보기위함일꺼같은데 
후자로 필요하다면 더미값을 조금더 추가하면 좋을듯하네요

### 도메인 서비스 위치
도메인 서비스면 구현체 DigginRoomPasswordEncoder 얘만 member 쪽으로 옮기면 좋을까요
아니면 DigginRoomPasswordEncoder, PasswordEncoder, HashAlgorithm 모든 코드를 member쪽으로 옮기는게 좋을까요
패스워드 암호화하는과정들을 전부 비즈니스로직으로 보고 member쪽으로 옮겨도 될거같네요

2023-11-09 02:05 UTC, kong-hana01 approved these changes
크게 말씀드릴 부분이 안보이네요!
파워가 구현해주신 내용은 1.0.0 버전까지 적용하고, 
`1.1.0 버전으로 업그레이드한 거는 self 회원 가입 기능을 제거`하는 건 어떨지 제안합니다~

추가로 질문 주신 부분에 대해서만 제 의견 전해드릴게용!

> Q. data.sql 이거 필요할까요?

현재 테스트에서 사용되지 않는다면 굳이 필요 없어보이네요!
현재 컨트롤러 테스트가 인수테스트 형식으로 되어있어서 굳이 필요없어 보이기도 하는데요.
나중에 필요하게 되면 `ControllerTest에서 beforeEach에 더미 데이터를 넣어줄지`, `data.sql에서 더미 데이터를 넣어줄지` 한번 논의해보면 좋을 것 같네요!

> Q. 도메인 서비스 위치

저는 DigginRoomPasswordEncoder만 member 쪽에 두면 좋을 것 같아요!
파워께서 PasswordEncoder를 인터페이스로 분리하신 이유가 추후에 security를 사용하게 될 때 변경 사항을 최소화하는 거로 생각했어요. 그래서 PasswordEncoder는 현재 패키지에 그대로 두고 구현체만 member로 가져와도 괜찮지 않나 생각합니다! 👍 


고생하셨습니당
테스트에 허덕이는 제 hp를 살리셨어요

2023-11-09 02:05 UTC, kong-hana01 commented on backend/src/test/java/com/digginroom/digginroom/controller/ControllerTest.java
> +    }
이거 저도 어제 이 방법이 생각나서 담주 쯤에 한번 작업해보려고 했는데 좋네용 bb

2023-11-14 12:33 UTC, Songusika requested changes
고생했습니다 파워!

덕분에 도메인 서비스가 무엇인지 계속해서 감이 잘 잡혀가는거 같아요
추가적으로 스프링 시큐리티가 제공하는 `PasswordEncoder` 인터페이스도 배워가네요!

데이터베이스 초기화 관련해서 리뷰 남겼습니다!
확인해보시구 의견주세용

2023-11-14 12:33 UTC, Songusika commented on backend/src/test/java/com/digginroom/digginroom/controller/ControllerTest.java
> +    }
Controller 테스트 이외에서도 사용할 수 있도록 Junit Extenstion 등록해보면 어떨까요??

`BeforeEachCallback` 은 매 `@BeforeEach` 이전에 수행됩니다!

```java
@Component
public class DatabaseCleaner {

    @Autowired
    private EntityManager entityManager;
    private List<String> tableNames;

    @PostConstruct
    private void setUpDatabaseTableNames() {
        this.tableNames = getTableNames();
    }

    private List<String> getTableNames() {
        return getTableMetaData().stream().map(this::getTableName).toList();
    }

    @SuppressWarnings("unchecked")
    private List<Object[]> getTableMetaData() {
        return entityManager.createNativeQuery("SHOW TABLES").getResultList();
    }

    private String getTableName(final Object[] tableInfos) {
        return (String) tableInfos[0];
    }

    @Transactional
    public void clear() {
        executeQuery("SET REFERENTIAL_INTEGRITY FALSE;");
        tableNames.forEach(tableName -> executeQuery("TRUNCATE TABLE " + tableName + " RESTART IDENTITY;"));
        executeQuery("SET REFERENTIAL_INTEGRITY TRUE;");
    }

    private void executeQuery(final String query) {
        entityManager.createNativeQuery(query).executeUpdate();
    }
}

```

```java
public class DatabaseCleanerExtension implements BeforeEachCallback {

    @Override
    public void beforeEach(final ExtensionContext context) throws Exception {
        SpringExtension.getApplicationContext(context)
                .getBean(DatabaseCleaner.class)
                .clear();
    }
} 
```

위와 같이 extension 으로 등록한 후 ExtendWith 어노테이션에 명시해서 사용할 수 있습니다!
```java
@ExtendWith(DatabaseCleanerExtension.class)
@DisplayNameGeneration(ReplaceUnderscores.class)
@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
public abstract class ControllerTest {
```

2023-11-14 12:44 UTC, Songusika approved these changes
고생했씁니다 파워~

2023-11-16 08:20 UTC, 0chil approved these changes
리뷰하려고 했더니 실시간으로 변하네요 ㅎㅎ
고생하셨습니다

2023-11-17 05:11 UTC, merged