feat: 기본적인 회원가입 기능을 구현한다.
woowacourse-teams/2023-diggin-room pull request #47
Opened 2023-07-18 05:05 UTC by kong-hana01

## 관련 이슈번호
- #46

## 작업 사항
- 회원가입 기능 구현
- 회원 도메인 구현

## 기타 사항
<br/>

2023-07-18 06:00 UTC, 0chil requested changes

2023-07-18 06:00 UTC, 0chil commented on backend/src/test/java/com/digginroom/digginroom/controller/GlobalExceptionHandlerTest.java
> -                .body("errorCode", equalTo("NONE"))
👍

2023-07-18 06:00 UTC, 0chil commented on backend/src/main/java/com/digginroom/digginroom/controller/dto/MemberSaveRequest.java
> +    }
Request -> 도메인 객체 변환을 여기서 해주는 이유가 있나요?
한 Request에 대해서만 적용되기 때문에 재사용성이 없기 때문일까요?

얘기 나눠본 결과 다음과 같은 단점이 있었네요:
- 변환 과정에 비즈니스 로직을 끼워넣을 수 없다
  - 예) 비밀번호를 암호화하는 로직을 끼워넣을 수 없다.

2023-07-18 06:00 UTC, 0chil commented on backend/src/main/java/com/digginroom/digginroom/service/MemberService.java
> +
트랜잭션으로 묶는것을 깜빡하신 것 같아요!

2023-07-18 06:00 UTC, 0chil commented on backend/src/main/java/com/digginroom/digginroom/domain/Member.java
> +@RequiredArgsConstructor
`@RequiredArgsConstructor`는 필요 없는 상황인 것 같습니다!

2023-07-18 06:00 UTC, 0chil commented on backend/src/main/java/com/digginroom/digginroom/exception/MemberException.java
> +    }
👍

2023-07-18 06:00 UTC, 0chil commented on backend/src/main/java/com/digginroom/digginroom/repository/MemberRepository.java
> +    Optional<Member> findByMemberId(String memberId);
```suggestion
    Optional<Member> findByMemberId(String memberId);
    
    boolean existsByMemberId(String memberId);
```

해당 `memberId`가 존재하는지 확인하는 메서드를 추가하면 어떨까요?

2023-07-18 06:00 UTC, 0chil commented on backend/src/main/java/com/digginroom/digginroom/service/MemberService.java
> +    }
이 부분은 제안입니다! 반영해달라는 뜻은 아닙니다 😄

결국 `Member` 도메인 객체를 만들거라면,
처음부터 `Member` 도메인 객체를 만들어두고 사용해도 좋지 않을까요?

추가로 `isDuplicated()` 함수 인자를 `Member`로 바꾸는 건 어떨까요?
멤버 중복 검증 로직을 캡슐화 해준다는 장점이 있을 것 같아요. 
핵심 도메인인 `Member` 단위로 사용할 수 있어서 좋을 것 같습니다!

멤버 중복 검증이 필요하다 -> `MemberService.isDuplicated()` 사용
`memberId`의 중복 검증이 필요하다 -> `MemberRepository.existsByMemberId()` 사용

```suggestion
    public void save(final MemberSaveRequest request) {
        Member member = request.toMember();
        if (isDuplicated(member)) {
            throw new DuplicationException();
        }
        memberRepository.save(member);
    }

    private boolean isDuplicated(Member member) {
        return memberRepository.existsByMemberId(member.getId());
    }

    public MemberDuplicationResponse checkDuplication(String memberId) {
        boolean duplicated = memberRepository.existsByMemberId(memberId);
        return new MemberDuplicationResponse(duplicated);
    }
```

2023-07-18 06:04 UTC, Songusika requested changes
구현하시느라 고생하셨습니다~ 🙇‍♂️
간단한 `final` 컨벤션과 `@NotBlank` 적용해주시면 좋겠습니다.

2023-07-18 06:06 UTC, 0chil commented on backend/src/main/java/com/digginroom/digginroom/controller/dto/MemberSaveRequest.java
> +        @NotNull(message = "비밀번호를 입력해주세요.") String password
길이를 정하는건 어떨까요?

2023-07-18 06:07 UTC, 0chil commented on backend/src/main/java/com/digginroom/digginroom/controller/MemberController.java
> +}
엔드포인트를 만든 기준이 있을까요?

2023-07-19 02:00 UTC, Songusika commented on backend/src/main/java/com/digginroom/digginroom/controller/MemberController.java
> +}
`Member` 의 `memberId`를 `username` 으로 변경하였으니
그 부분도 반영하면 어떨까요?

2023-07-19 02:01 UTC, 0chil commented on backend/src/main/java/com/digginroom/digginroom/controller/MemberController.java
> +}
`GET /members/{memberId}/exist` 이런식으로 표현이 가능하지 않을까요?
'존재여부'를 '가져온다' 라는 의미로 해석될 수 있을 것 같은데, 어떻게 생각하시나요?

2023-07-19 02:05 UTC, 0chil commented on backend/src/main/java/com/digginroom/digginroom/controller/dto/MemberSaveRequest.java
> +) {
아이디, 비밀번호 길이나 사용가능한 문자에 대한 검증은 입력 단계에서도 필요하겠지만,
도메인 객체에 더 필요할 할 것 같은데, 어떻게 생각하시나요!

2023-07-19 04:45 UTC, Songusika approved these changes
세션/토큰과 같이 공부하면서 구현하시느라 고생하였습니다 👍

2023-07-19 04:45 UTC, 0chil approved these changes
고생하셨습니다.
검증에 관한 내용은 담주 할 내용으로 issue에 올려두었습니다.

2023-07-19 04:47 UTC, merged