2차 데모데이 결과물 반영
woowacourse-teams/2023-diggin-room pull request #86
Opened 2023-07-25 01:18 UTC by boogi-woogi

## 관련 이슈번호
- #85 

## 작업 사항
2차 데모데이 결과물 반영

## 기타 사항
<br/>

2023-07-25 01:21 UTC, thdwoqor approved these changes

2023-07-25 01:22 UTC, Songusika requested changes
필요없는 사진은 지워주세요~

2023-07-25 01:29 UTC, 0chil approved these changes

2023-07-25 08:51 UTC, Songusika approved these changes
2차 데모 구현하시느라 고생하셨습니다 👍

2023-07-26 01:46 UTC, kong-hana01 approved these changes
lgtm

2023-07-26 01:46 UTC, whk06061 approved these changes

2023-07-26 01:46 UTC, merged