Feature/84
woowacourse-teams/2023-diggin-room pull request #94
Opened 2023-07-26 08:36 UTC by boogi-woogi

## 관련 이슈번호
- #84 

## 작업 사항
* LoginActivity, JoinActivity에 존재하는 로그인 성공했을 때 동작하는 함수, 실패했을 때 동작하는 함수 혹은 다른 액티비티로의 이동을 수행하는 함수를 interface를 통해 다른 클래스로 분리했습니다.
* xml에서 변수처럼 존재하던 id, password들을 ViewModel의 변수들과 연결했습니다. 
  * xml, 즉 view라고 여겨지는 곳에서 데이터의 상태를 가지고 있는 것이 옳지 않다고 생각합니다.
* NonNullMutableLiveData를 만들었습니다.
  * livedata의 코드를 살펴보면 데이터가 셋팅되지 않았을 때 null을 return하는 기본 코드가 존재합니다.
![image](https://github.com/woowacourse-teams/2023-diggin-room/assets/88770426/6a21881c-506c-49ed-ad69-a1867d31dccd)
  * 때문에 MutableLiveData의 기본 값이 null이 아닌 타입으로 셋팅되어 있음에도 불구하고(절대로 value가 null이 아닌 상황) null을 확인해야 하는 불필요한 상황을 막기 위함입니다. (아래 사진과 같이)
![image](https://github.com/woowacourse-teams/2023-diggin-room/assets/88770426/abbe952a-6d59-405f-9d3a-7850b343926f)

## 기타 사항
<br/>

2023-07-26 08:54 UTC, whk06061 requested changes

2023-07-26 08:54 UTC, whk06061 commented on android/app/src/main/java/com/digginroom/digginroom/views/activity/JoinActivity.kt
> -
View 에서 ResultListener 를 구현하는 방법에서 viewmodel 에 인터페이스를 주입하는 방식으로 변경한 이유는 뭔가요?! 어떤 이점이 있을까요?!

2023-07-26 08:55 UTC, whk06061 approved these changes

2023-07-27 01:37 UTC, DYGames approved these changes

2023-07-27 01:37 UTC, DYGames commented on android/app/src/main/java/com/digginroom/digginroom/views/activity/JoinNavigator.kt
> +interface JoinNavigator {
이 인터페이스에 대해 유일한 구현체의 접두사를 Default로 두었던데, 다른 계층으로 분리하기 위해 인터페이스와 그 구현체를 둔게 아니라면(Repository와 같이) Default 대신 추상적인 인터페이스 이름과 명시적인 구현체 이름으로 바꾸는게 어떨까요

2023-07-27 04:48 UTC, boogi-woogi commented on android/app/src/main/java/com/digginroom/digginroom/views/activity/JoinNavigator.kt
> +interface JoinNavigator {
인터페이스 이름을 -> JoinNavigationHandler / LoginNavigationHandler
구현체 이름을 -> JoinNavigator / LoginNavigator라고 변경했습니다.

혹시 코건이 생각하는 더 좋은 이름이 있을까요?

2023-07-27 04:53 UTC, boogi-woogi commented on android/app/src/main/java/com/digginroom/digginroom/views/activity/JoinActivity.kt
> -
Activity내에서 회원가입이 성공했을 때, 로그인이 실패했을 때에 대한 처리를 신경쓰지 않아도 됩니다.  Activity에서는 객체를 binding에 연결하고 JoinResultListener은 성공, 실패에 대한 처리에 대한 책임만 갖기 때문에 역할 분리가 잘 이루어진다고 생각합니다~

2023-07-27 12:51 UTC, merged